services:
  server:
    build:
      context: .
      target: final
    environment:
      ASPNETCORE_URLS: http://+:5291
    depends_on: 
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: texus-find12345VadQWE#
      MYSQL_DATABASE: programming_site
      MYSQL_USER: vadimkirpikov
      MYSQL_PASSWORD: texus-find12345VadQWE#
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
